import MDAvatar from "/components/MDAvatar";
import Icon from "@mui/material/Icon";
import { user, logout } from "../context/AuthContext";
import profilePicture from "/assets/images/team-3.jpg";

const routes = [
  {
    type: "collapse",
    name: user ? `${user?.user?.first_name} ${user?.user?.last_name}` : "Login",
    key: "brooklyn-alice",
    icon: <MDAvatar src={profilePicture.src} alt="Brooklyn Alice" size="sm" />,
    collapse: [
      {
        name: "My Profile",
        key: "my-profile",
        route: "/pages/profile/profile-overview",
      },
      {
        name: "Settings",
        key: "profile-settings",
        route: "/pages/account/settings",
      },
      {
        name: "Logout",
        key: "logout",
        route: { logout },
      },
    ],
  },
  { type: "divider", key: "divider-0" },
  {
    type: "collapse",
    name: "Inicio",
    key: "dashboards",
    icon: <Icon fontSize="medium">home</Icon>,
    route: "/dashboards/sales",
    noCollapse: true,
  },
  { type: "title", title: "Ventas", key: "sales-pages" },
  {
    type: "collapse",
    name: "Embudo",
    key: "crm-pipeline",
    icon: <Icon fontSize="medium">view_kanban</Icon>,
    route: "/crm/pipeline",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Lista",
    key: "crm-list",
    icon: <Icon fontSize="medium">view_list</Icon>,
    route: "/crm/list",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Clientes",
    key: "crm-customers",
    icon: <Icon fontSize="medium">group</Icon>,
    route: "/customers",
    noCollapse: true,
  },
  { type: "title", title: "Legales", key: "legal-pages" },
  {
    type: "collapse",
    name: "Causas",
    key: "causes",
    icon: <Icon fontSize="medium">balance</Icon>,
    route: "/causes",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Calculadoras",
    key: "causes-calculators",
    icon: <Icon fontSize="medium">calculate</Icon>,
    route: "/calculators",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Consultas",
    key: "causes-consultation",
    icon: <Icon fontSize="medium">forum</Icon>,
    route: "/consultation",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Documentos",
    key: "causes-documents",
    icon: <Icon fontSize="medium">assignment_ind</Icon>,
    route: "/cause/documents",
    noCollapse: true,
  },
  { type: "title", title: "Contable", key: "finance-pages" },
  {
    type: "collapse",
    name: "Acuerdos",
    key: "finance-agreement",
    icon: <Icon fontSize="medium">handshake</Icon>,
    route: "/finances/agreement",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Caja",
    key: "finance-cash",
    icon: <Icon fontSize="medium">account_balance</Icon>,
    route: "/finances/cash",
    noCollapse: true,
  },
  { type: "title", title: "Aplicaciones", key: "application-pages" },
  {
    type: "collapse",
    name: "Nube",
    key: "application-cloud",
    icon: <Icon fontSize="medium">cloud</Icon>,
    route: "/cloud",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Calendario",
    key: "application-calender",
    icon: <Icon fontSize="medium">calendar_month</Icon>,
    route: "/calender",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Tareas",
    key: "application-tasks",
    icon: <Icon fontSize="medium">tasks</Icon>,
    route: "/tasks",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Rutas",
    key: "application-routes",
    icon: <Icon fontSize="medium">routes</Icon>,
    route: "/routes",
    noCollapse: true,
  },
  { type: "title", title: "Estadisticas", key: "statistics-pages" },
  {
    type: "collapse",
    name: "Ventas",
    key: "statistics-sales",
    icon: <Icon fontSize="medium">trending_up</Icon>,
    route: "/statistics/sale",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Legales",
    key: "statistics-legal",
    icon: <Icon fontSize="medium">bar_chart</Icon>,
    route: "/statistics/legal",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Marketing",
    key: "statistics-analytics",
    icon: <Icon fontSize="medium">analytics</Icon>,
    route: "/statistics/analytics",
    noCollapse: true,
  },
  {
    type: "collapse",
    name: "Contable",
    key: "statistics-finance",
    icon: <Icon fontSize="medium">account_balance_wallet</Icon>,
    route: "/statistics/finance",
    noCollapse: true,
  },
  { type: "divider", key: "divider-1" },
  {
    type: "collapse",
    name: "Chat",
    key: "chat",
    icon: <Icon fontSize="medium">chat</Icon>,
    route: "/chat",
    noCollapse: true,
  },
];

export default routes;
